### PR TITLE
fix(errors): body can be null (or undefined)

### PR DESCRIPTION
**Pull request by plchampigny**
This PR fixes an issue when having 401 from package registries without body.

### CODE REVIEW

**Comment by plchampigny** [comment]
Related to https://github.com/npm/npm-registry-fetch/issues/6

**Comment by isaacs** [comment]
Needs a test, but we can add that if you don't get to it.  This is definitely a bug.  Thanks!

**Comment by isaacs** [comment]
Hm, I think as of https://github.com/npm/npm-registry-fetch/pull/11 the body actually _can't_ be undefined or null.  If the server doesn't return a response, it'll just be a zero-length buffer object.

**Comment by plchampigny** [comment]
Well thank you for the follow up!

**Pull request closed without merging**
